GET http://localhost:5000/api/occupation

###

GET http://localhost:5000/api/occupation/2

###

POST http://localhost:5000/api/occupation/
Content-Type: application/json

{
   "occupation": "Doctor",
   "pekerjaan": "Dokter"
}

###

PUT http://localhost:5000/api/occupation/1
Content-Type: application/json

{
     "occupation": "Judge"

}

###

DELETE http://localhost:5000/api/occupation/26
Content-Type: application/json

{

}

###

